FROM nginx:1.19.6-alpine
COPY ./dist/ /usr/share/nginx/html/
RUN echo -e "http://nl.alpinelinux.org/alpine/v3.5/main\nhttp://nl.alpinelinux.org/alpine/v3.5/community" > /etc/apk/repositories
RUN apk update
RUN apk add tzdata

